version: '3.8'

services:
  spring_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_PROFILES_ACTIVE: production
    ports:
      - "8080:8080"
    networks:
      - backend


volumes:
  mysql_data:

networks:
  backend:
