spring:
  datasource:
    url: jdbc:mysql://mysql:3306/youtube_bookmark?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # synchronized
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: redis
    port: 6379

server:
  port: 8080
