spring:
  datasource:
    url: jdbc:mysql://localhost:3306/youtube_bookmarker?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 3000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          fetch_size: 30
        order_inserts: true
        order_updates: true


server:
  port: ${PORT}
  address: 0.0.0.0
  shutdown: graceful
  tomcat:
    max-threads: 50
    min-spare-threads: 10
    accept-count: 50
    connection-timeout: 3000

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.mag1c.youtube-bookmark: INFO
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 14


youtube:
  api-key: ${YOUTUBE_API_KEY}